name: "Build iOS IPA"

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Cette étape répare l'erreur "Application not configured for iOS"
      - name: Create iOS configuration
        run: flutter create . --platforms=ios

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS (IPA manuel)
        run: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r iphone-transfer.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iphone-transfer-app
          path: build/ios/iphoneos/iphone-transfer.ipa
