name: "Build iOS IPA"

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create iOS configuration
        run: flutter create . --platforms=ios

      - name: Get dependencies
        run: flutter pub get

      - name: Build and Sign IPA
        run: |
          flutter build ios --release --no-codesign
          # On laisse Flutter tenter de gérer la structure
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          # On crée le ZIP nous-mêmes proprement
          zip -r iphone-transfer.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iphone-transfer-ipa
          path: iphone-transfer.ipa
